_BASE_: Base-PointRend-RCNN-FPN.yaml
MODEL:
  WEIGHTS: "/home/media4us/PycharmProjects/detectron2/projects/PointRend/weights/model_final_3c3198.pkl"
  MASK_ON: true
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
# To add COCO AP evaluation against the higher-quality LVIS annotations.
# DATASETS:
#   TEST: ("coco_2017_val", "lvis_v0.5_val_cocofied")

